
class DatenImportError(Exception):
    '''Steht fÃ¼r Fehler beim Datenimport'''

    def __init__(self, *args: object) -> None:
        super().__init__(*args)

    